"""SQLAlchemy model export surface."""

from __future__ import annotations

from app.db.base import Base
from app.db.models.aggregation import (
    AGGREGATION_MODELS,
    AggregationSession,
    AggregationSessionItem,
)
from app.db.models.batch import BATCH_MODELS, BatchSession, BatchSessionItem
from app.db.models.collections import (
    COLLECTION_MODELS,
    Collection,
    CollectionCollaborator,
    CollectionInvite,
    CollectionItem,
)
from app.db.models.core import (
    CORE_MODELS,
    AttachmentProcessing,
    AudioGeneration,
    AuditLog,
    Chat,
    ClientSecret,
    CrawlResult,
    LLMAttemptTrigger,
    LLMCall,
    ProgressEvent,
    RefreshToken,
    Request,
    RequestProcessingJob,
    Summary,
    SummaryEmbedding,
    TelegramMessage,
    User,
    UserCredential,
    UserDevice,
    UserInteraction,
    VideoDownload,
    XBookmarkMetadata,
    XCategory,
)
from app.db.models.digest import (
    DIGEST_MODELS,
    Channel,
    ChannelCategory,
    ChannelPost,
    ChannelPostAnalysis,
    ChannelSubscription,
    DigestDelivery,
    UserDigestPreference,
)
from app.db.models.git_backup import (
    GIT_BACKUP_MODELS,
    GitMirror,
    GitMirrorSource,
    GitMirrorStatus,
)
from app.db.models.repository import (
    REPOSITORY_MODELS,
    GitHubAuthMethod,
    GitHubIntegrationStatus,
    Repository,
    RepositoryEmbedding,
    RepoSource,
    UserGitHubIntegration,
)
from app.db.models.rss import RSS_MODELS, RSSFeed, RSSFeedItem, RSSFeedSubscription, RSSItemDelivery
from app.db.models.rules import (
    RULE_MODELS,
    AutomationRule,
    ImportJob,
    RuleExecutionLog,
    UserBackup,
    WebhookDelivery,
    WebhookSubscription,
)
from app.db.models.signal import SIGNAL_MODELS, FeedItem, Source, Subscription, Topic, UserSignal
from app.db.models.social import (
    SOCIAL_MODELS,
    SocialAuthState,
    SocialAuthStateStatus,
    SocialAuthType,
    SocialConnection,
    SocialConnectionStatus,
    SocialFetchAttempt,
    SocialFetchAttemptStatus,
    SocialProvider,
)
from app.db.models.topic_search import TOPIC_SEARCH_MODELS, TopicSearchIndex
from app.db.models.transcription import (
    TRANSCRIPTION_MODELS,
    TranscriptionArtifact,
    TranscriptionJob,
    TranscriptionProgressEvent,
)
from app.db.models.user_content import (
    USER_CONTENT_MODELS,
    CustomDigest,
    SummaryFeedback,
    SummaryHighlight,
    SummaryTag,
    Tag,
    UserGoal,
)
from app.db.models.webwright import (
    WEBWRIGHT_MODELS,
    UserBrowserSession,
    WebwrightRun,
    WebwrightRunStatus,
)
from app.db.types import _next_server_version, _utcnow, model_to_dict

ALL_MODELS: tuple[type[Base], ...] = (
    *CORE_MODELS,
    *AGGREGATION_MODELS,
    *BATCH_MODELS,
    *COLLECTION_MODELS,
    *DIGEST_MODELS,
    *GIT_BACKUP_MODELS,
    *REPOSITORY_MODELS,
    *RSS_MODELS,
    *RULE_MODELS,
    *SIGNAL_MODELS,
    *SOCIAL_MODELS,
    *TOPIC_SEARCH_MODELS,
    *TRANSCRIPTION_MODELS,
    *USER_CONTENT_MODELS,
    *WEBWRIGHT_MODELS,
)

__all__ = [
    "AGGREGATION_MODELS",
    "ALL_MODELS",
    "BATCH_MODELS",
    "COLLECTION_MODELS",
    "CORE_MODELS",
    "DIGEST_MODELS",
    "GIT_BACKUP_MODELS",
    "REPOSITORY_MODELS",
    "RSS_MODELS",
    "RULE_MODELS",
    "SIGNAL_MODELS",
    "SOCIAL_MODELS",
    "TOPIC_SEARCH_MODELS",
    "TRANSCRIPTION_MODELS",
    "USER_CONTENT_MODELS",
    "WEBWRIGHT_MODELS",
    "AggregationSession",
    "AggregationSessionItem",
    "AttachmentProcessing",
    "AudioGeneration",
    "AuditLog",
    "AutomationRule",
    "Base",
    "BatchSession",
    "BatchSessionItem",
    "Channel",
    "ChannelCategory",
    "ChannelPost",
    "ChannelPostAnalysis",
    "ChannelSubscription",
    "Chat",
    "ClientSecret",
    "Collection",
    "CollectionCollaborator",
    "CollectionInvite",
    "CollectionItem",
    "CrawlResult",
    "CustomDigest",
    "DigestDelivery",
    "FeedItem",
    "GitHubAuthMethod",
    "GitHubIntegrationStatus",
    "GitMirror",
    "GitMirrorSource",
    "GitMirrorStatus",
    "ImportJob",
    "LLMAttemptTrigger",
    "LLMCall",
    "ProgressEvent",
    "RSSFeed",
    "RSSFeedItem",
    "RSSFeedSubscription",
    "RSSItemDelivery",
    "RefreshToken",
    "RepoSource",
    "Repository",
    "RepositoryEmbedding",
    "Request",
    "RequestProcessingJob",
    "RuleExecutionLog",
    "SocialAuthState",
    "SocialAuthStateStatus",
    "SocialAuthType",
    "SocialConnection",
    "SocialConnectionStatus",
    "SocialFetchAttempt",
    "SocialFetchAttemptStatus",
    "SocialProvider",
    "Source",
    "Subscription",
    "Summary",
    "SummaryEmbedding",
    "SummaryFeedback",
    "SummaryHighlight",
    "SummaryTag",
    "Tag",
    "TelegramMessage",
    "Topic",
    "TopicSearchIndex",
    "TranscriptionArtifact",
    "TranscriptionJob",
    "TranscriptionProgressEvent",
    "User",
    "UserBackup",
    "UserBrowserSession",
    "UserCredential",
    "UserDevice",
    "UserDigestPreference",
    "UserGitHubIntegration",
    "UserGoal",
    "UserInteraction",
    "UserSignal",
    "VideoDownload",
    "WebhookDelivery",
    "WebhookSubscription",
    "WebwrightRun",
    "WebwrightRunStatus",
    "XBookmarkMetadata",
    "XCategory",
    "_next_server_version",
    "_utcnow",
    "model_to_dict",
]
